### ISSUE TITLE
external resource modification behaviour

### ISSUE THREAD

**Issue by kshpytsya** [nazarewk/terraform-provider-shell#1]
This may be a misunderstanding on my side but please clarify.

I have installed `terraform-provider-scripted` by issuing

```
go get github.com/nazarewk/terraform-provider-scripted
```

and tried your example:

```
provider "scripted" {
  create_command = "echo \"hi\" > test_file"
  read_command = "echo -n \"out=$(cat test_file)\""
  delete_command = "rm test_file"
}

resource "scripted_resource" "test" {
}
```

So far so good. `apply` and `destroy` work as expected.
However, if I do `apply` and the manually modify the `test_file`, and do `apply` again, the behaviour is somewhat surprising, at least to me: no actions are taken.

Doing `strace` I can see that `read_command` gets executed, and also I see `terraform.tfstate` is updated with updated contents of `test_file`.

My initial expectation was that in the above-mentioned scenario `apply` would just cause the original content (`hi`) be restored to the file, and the plan showing either `delete`/`create` or `update` (oops, no update in this example). On the other hand, trying similar scenario with `dns_a_record_set` of `dns` provider, where after the first `apply` I manually edit `dns` record on dns server, on the second `apply` I get:

```
Error: Error refreshing state: 1 error(s) occurred:

* dns_a_record_set.one: 1 error(s) occurred:
* dns_a_record_set.one: dns_a_record_set.one: DNS record differs
```

So, I cannot say for sure, which behaviour is better or more in vein with Terraform guidelines but the current behaviour of silence just does not seem correct.

**Comment by nazarewk** [comment]
Nice to see some interest in the provider.

I will look into it having example of working provider.

**Comment by nazarewk** [comment]
I have managed to get it to work with `commands_should_update`
Note that i have renamed and refactored most of the parameters

The new example would be:
```hcl
provider "scripted" {
  alias = "file"
  commands_should_update = <<EOF
[ "$(cat '{{ .Cur.path }}')" == '{{ .Cur.content }}' ] || exit 1
EOF
  commands_create = "echo -n '{{ .Cur.content }}' > '{{ .Cur.path }}'"
  commands_read = "echo -n \"out=$(cat '{{ .Cur.path }}')\""
  commands_delete = "rm '{{ .Cur.path }}'"
}
resource "scripted_resource" "test" {
  provider = "scripted.file"
  context {
    path = "test_file"
    content = "hi"
  }
}
```
